#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  5 11:11:16 2023

@author: mykolakotliarenko
"""

import requests
from bs4 import BeautifulSoup
url= 'http://www.nytimes.com/'
response=requests.get(url).text
soup=BeautifulSoup(response,"html.parser")
l=[]
for title in soup.find_all('h3'):
    print(title.contents[0])